name: Go CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.0'  # 选择你使用的 Go 版本

      - name: Initialize modules
        run: go mod init IAM  # 替换为你的项目名称

      - name: Install dependencies
        run: go mod download

      - name: Run unit tests
        run: go test -v ./...

      - name: Run static code analysis
        run: |
          curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s v1.43.0
          golangci-lint run